name: Publish

on:
  push:
    branches: [ master ]

jobs:
  coveralls:
    name: Coveralls
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: ts-serializer-coverage

      - name: Send coverage to Coverall
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: ts-serializer

      - name: Publish @paddls
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^release: v(\\S+)"
          publish_args: "--access public"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}

      - name: PrePublish @witty-services
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: name
          value: "@witty-services/ts-serializer"

      - name: Publish @witty-services
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          commit_pattern: "^release: v(\\S+)"
          publish_args: "--access public"
          create_tag: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}
